export const movieMock = JSON.stringify({
  title: 'Человек-паук: Нет пути домой',
  plot: 'Жизнь и репутация Питера Паркера оказываются под угрозой, поскольку Мистерио раскрыл всему миру тайну личности Человека-паука. Пытаясь исправить ситуацию, Питер обращается за помощью к Стивену Стрэнджу, но вскоре всё становится намного опаснее.',
  year: '2021',
  director: 'Джон Уоттс',
  actors: [
    'Том Холланд',
    'Зендея',
    'Бенедикт Камбербэтч',
    'Мариса Томей',
    'Уиллем Дефо',
    'Альфред Молина',
    'Джейми Фокс',
    'Томас Хейден Чёрч',
    'Рис Иванс',
    'Джейкоб Баталон'
  ],
  poster: 'https://s.rutor.org/imgproxy.php?url=http://lostpix.com/thumbs/2022-10/20/nzvcef43fj0iz2sx81mioj2xy.png',
  trailer: 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
  boxOffice: '',
  released: '2021',
  writer: 'Крис МакКенна',
  runtime: '148',
  ratingImdb: '8.3',
  imdbId: 'tt10872600',
  rated: 'PG-13 ',
  genres: ['Фантастика', 'боевик', 'приключения', 'фэнтези'],
  fileName: 'ChelovekPaukNetPutiDomojWEBDLRip1080p.mkv',
  magnet: 'e06f9f7513321454b8d023e879a9980441dcd385',
  sourceUrl: 'https://rutor.org/torrent/893033'
})
